[package]
name = "openapi-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = "0.13.4"
anyhow = "1.0.94"
camino = "1.1.9"
clap = { version = "4.5.23", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["debug"] }
fs-err = "3.0.0"
heck = "0.5.0"
indexmap = "2.7.0"
itertools = "0.13.0"
minijinja = { version = "2.5.0", features = ["loader"] }
schemars = "0.8.21"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sha2 = "0.10.8"
tempfile = "3.14.0"
toml = { version = "0.8.19", default-features = false, features = ["parse"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
